.TH CATFISH "1" "August 2014" "catfish 1.2.0" "User Commands"
.SH NAME
catfish \- File searching tool which is configurable via the command line
.SH "DESCRIPTION"
.B Catfish
is a handy file searching tool for Linux and UNIX. 
The interface is intentionally lightweight and simple, using only Gtk+3. 
You can configure it to your needs by using several command line options.
.SH SYNOPSIS
.B catfish
[\fI\,options\/\fR] \fI\,path query\/\fR
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show debug messages (\fB\-vv\fR debugs catfish_lib also)
.TP
\fB\-\-large\-icons\fR
Use large icons
.TP
\fB\-\-thumbnails\fR
Use thumbnails
.TP
\fB\-\-iso\-time\fR
Display time in ISO format
.TP
\fB\-\-exact\fR
Perform exact match
.TP
\fB\-\-hidden\fR
Include hidden files
.TP
\fB\-\-fulltext\fR
Perform fulltext search
.TP
\fB\-\-start\fR
If path and query are provided, start searching when the
application is displayed.
